d1=read.csv(file.choose(),header = T)
View(d1)
d2=d1
colnames(d2)=c("St","Q","L")
View(d2)
summary(d2$Q)
var(d2$Q)
sd(d2$Q)
cor(d2$Q,d2$St)
cov(d2$Q,d2$St)
mean(d2$Q,trim=0.10)
plot(d2$Q,d2$St,main="scatter diagram 1")
plot(d2$Q,d2$St,main = "scatter diagram 1",xlab = "Urban population",ylab = "Fertility rate")
abline(lm(d2$St~d2$Q))
Reg1=lm(d2$St~d2$Q)
View(Reg1)
summary(Reg1)
Reg2=lm(d2$St~d2$Q+d2$L)
summary(Reg2)
plot(Reg1)
RS1=residuals(Reg1)
RS1sq=RS1^2
View(RS1sq)
d3=cbind(d2,RS1sq)
View(d3)
anova(Reg1)
jarque.bera.test(residuals(Reg1))
summary(d2$L)
var(d2$L)
sd(d2$L)
cor(d2$L,d2$St)
cov(d2$L,d2$St)
mean(d2$L,trim=0.10)
plot(d2$L,d2$St,main = "Scatter diagram",xlab = "Income",ylab = "Fertility Rate")
abline(lm(d2$St~d2$L))
Reg3=lm(d2$St~d2$L)
View(Reg3)
summary(Reg3)
plot(Reg3)
RS3=residuals(Reg3)
RS3sq=RS3^4
View(RS3sq)
d4=cbind(d3,RS3sq)
View(d4)
anova(Reg3)
jarque.bera.test(residuals(Reg3))
plot(Reg2)
plot(d2$Q,d2$L,d2$St,main = "MULTIPLE LINEAR REGRESSION",xlab = "Urban Population",ylab = "Income")
 anova(Reg2)
jarque.bera.test(residuals(Reg2)) 
